name: image_to_text_converter_getx_fixed
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  #  firebase_ml_custom: ^0.2.0+3
  get: ^4.3.8
  google_ml_kit: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/back.jpg
    - assets/note.jpg
    - assets/pin.png
    - assets/imagetext.png